org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.256
neo_version_range=[21.1.0,)
loader_version_range=[1,)

ars_version=5.13.3.1423

mod_id=arsmanahud
mod_name=Ars Mana HUD
mod_license=GNU LGPLv3
mod_version=1.0.0
mod_group_id=io.github.agwstin.arsmanahud
mod_authors=Agwstin, WFPhantom
mod_description=Adds numbers to your mana bar and mana use tooltips on glyphs.