modLoader="javafml" #mandatory

loaderVersion="${loader_version_range}" #mandatory

license="${mod_license}"

issueTrackerURL="https://github.com/WFPhantom/ArsNumericHUD/issues"

[[mods]] #mandatory

modId="${mod_id}" #mandatory

version="${mod_version}" #mandatory

displayName="${mod_name}" #mandatory

#updateJSONURL="https://change.me.example.invalid/updates.json" #optional

displayURL="https://modrinth.com/mod/ars-numerichud" #optional

logoFile="arsnumerichud.png" #optional

credits="Moonwolf, Sarenor, Alexth99" #optional

authors="${mod_authors}" #optional

description='''${mod_description}'''

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]] #optional
    modId="neoforge" #mandatory
    type="required" #mandatory
    versionRange="[${neo_version},)" #mandatory
    ordering="NONE"
    side="CLIENT"

# Here's another dependency
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="CLIENT"

[[dependencies.${mod_id}]]
    modId="ars_nouveau"
    type="required"
    versionRange="[5.6.0,)"
    ordering="NONE"
    side="CLIENT"